# H2 Database Configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  show-login-endpoint: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method

server:
  error:
    include-stacktrace: never
